proshore/TickerPRO-ProshoreTimeTrackingSystem-Backend

resources/views/welcome.blade.php
=> link removed

resources/views/welcome.blade.php
=> PTT-24 #comment unused spacing removed

resources/views/welcome.blade.php
=> PTT-9 #comment unused space removed

app/Models/TimeLog.php, app/Services/TimeLogService.php
I have declared return type for eloquent relationship user() method which i forgot to do and also made some changes in viewTImeLogs method to retrieve particular user timelogs...
=> PTTB-12 declare return type & modify viewTimeLogs method

composer.json, composer.lock, database/migrations/2022_08_31_135013_change_role_id_type_invite_tokens_table.php, database/migrations/2022_08_31_152752_change_client_id_type_projects_table.php, database/migrations/2022_08_31_153415_change_user_id_project_id_type_user_projects_table.php, database/migrations/2022_08_31_154447_change_user_id_type_project_id_type_time_logs_table.php, database/migrations/2022_08_31_154930_change_user_id_type_role_id_type_user_roles_table.php
Installed 3rd party doctorine/dbal package and maintain foreign key constraint generation new migration for related columns.
=> PTTB-12 New migration files created maintaining foreignKey constraint

app/Http/Requests/AddTimeLogRequest.php, app/Http/Requests/ClientRequest.php, app/Http/Requests/EditTimeLogRequest.php, app/Http/Requests/MemberInviteRequest.php, app/Http/Requests/ProjectRequest.php, app/Http/Requests/UserStoreRequest.php
I have removed custom messages for 'required' named validation rule bcoz laravel will provide message automatically if validation rule is not matched...
=> PTTB-10 custom msgs removed for 'required' validation rule

app/Http/Resources/InviteResource.php
=> PTTB-7 invitedUserId changed to id for InviteResource

app/Http/Requests/ClientRequest.php
What happened?
- Client Number field only accepts values upto 255. 
What should happen?
- Client Number field should only accept a 10 digit mobile number.
- Custom error messages for different errors
=> Client number accepts 10 digit mobile number

app/Http/Controllers/ClientController.php, app/Http/Controllers/ProjectController.php, app/Http/Requests/ClientRequest.php, app/Http/Resources/ClientResource.php, app/Http/Resources/ProjectResource.php, app/Models/Client.php, composer.lock
to the send the projects related to the client as well in the api
=> added projects column to clients list

app/Http/Controllers/ProjectController.php, app/Http/Resources/ClientResource.php, app/Http/Resources/ProjectResource.php
replaced resource collection with new resource
=> PTTB-288 replaced resource collection with new

app/Http/Controllers/AdminController.php
User does not exists message should be displayed
=> Pttb 295 500 error on user role endpoint for non existent user

app/Http/Requests/PasswordResetRequest.php
All special character are supported now.
=> special character are now supported

app/Http/Controllers/Actions/Auth/RegisterAction.php, app/Http/Controllers/AuthController.php, app/Http/Controllers/UserController.php, app/Http/Requests/UserStoreRequest.php, app/Http/Resources/UserResource.php, app/Rules/CheckHashedToken.php, app/Services/UserService.php, routes/api.php
registration function refactored.
refactored:
-> Validation is done from request
-> created rule to check token expiry and validity
=> PTTB-231 registration code refactored

app/Exceptions/Handler.php, app/Http/Controllers/ClientController.php, app/Services/ClientService.php, routes/api.php
=> Pttb 84 backend delete client

app/Http/Controllers/Actions/Auth/LoginAction.php, app/Http/Controllers/AuthController.php, app/Services/UserService.php, routes/api.php
Refactored login to use a single action controller
=> Pttb 302 refactor login

app/Http/Controllers/TimeLogController.php, app/Services/TimeLogService.php
very urgent !!!
retreived latest timelogs and response format changed.
=> change response format and retrieve latest timelogs

app/Http/Controllers/TimeLogController.php, app/Services/TimeLogService.php
urgent!!!
changed response format and retrieve latest timelog
=> Get latest timelogs

app/Http/Requests/AddClientRequest.php
=> made client number unique

app/Http/Resources/UserResource.php, app/Services/UserService.php
changed login response so it shows user roles as well
=> changed login response

app/Http/Controllers/Actions/Report/GenerateReportAction.php, app/Services/ReportService.php
=> getUsersReport service created

app/Http/Requests/TimelogReportRequest.php, app/Services/ReportService.php
=> Pttb 361 total time logged

app/Http/Requests/MemberInviteRequest.php
email format validation changed
=> Pttb 350 backend format of email address

app/Http/Controllers/Actions/Admin/UpdateUserStatusAction.php, app/Http/Controllers/AdminController.php, app/Http/Middleware/CheckUserActiveStatus.php, app/Services/UserService.php, routes/api.php
requirements:
1. admin should not be able to disble themself but can disable other users and admin
2. show a custom message if user is disabled
=> PTTB-235 admin can now disable others but cannot disable itself

app/Http/Requests/TimelogReportRequest.php, app/Services/ReportService.php
=> added filtering by projects option

app/Http/Requests/AddClientRequest.php, app/Http/Requests/EditTimeLogRequest.php
removed the required validation from edit timelog function, so user can live edit the timelog
=> removed required from edit timelog fucntion

app/Http/Requests/AddClientRequest.php, app/Http/Requests/AssignRoleRequest.php, app/Http/Requests/EditClientRequest.php, app/Http/Requests/PasswordResetRequest.php, app/Http/Requests/UserLoginRequest.php, app/Http/Requests/UserStoreRequest.php
updated email validation in other places as well
=> updated email validation

app/Http/Controllers/Actions/Admin/DeleteUserAction.php, app/Http/Controllers/Actions/Admin/UpdateUserStatusAction.php, app/Http/Controllers/Actions/Auth/ForgotPasswordAction.php, app/Http/Controllers/Actions/Auth/LoginAction.php, app/Http/Controllers/Actions/Auth/LogoutAction.php, app/Http/Controllers/Actions/Auth/RegisterAction.php, app/Http/Controllers/Actions/Auth/ResetPasswordAction.php, app/Http/Controllers/Actions/Auth/VerifyInviteTokenAction.php, app/Http/Controllers/Actions/Auth/VerifyPasswordTokenAction.php, app/Http/Controllers/Actions/Report/GeneratePdfAction.php, app/Http/Controllers/Actions/Report/GenerateReportAction.php, app/Http/Controllers/AdminController.php, app/Http/Controllers/ClientController.php, app/Http/Controllers/Controller.php, app/Http/Controllers/TimeLogController.php, app/Http/Requests/ValidateInviteTokenRequest.php, app/Services/InviteService.php, routes/api.php
the inivite token sent to user should be verified to check if the token is actually real or not before opening the signup page
if not real then it provides message saying the token is invalid
=> Pttb 351 validate signup token

app/Http/Controllers/UserController.php
send users roles as well when hitting users/me route
=> sent roles with user details

app/Http/Requests/TimelogReportRequest.php
the end date must be required and should be after the start date
=> end date must be after start date

app/Http/Controllers/UserController.php
fixed bug with loading user details
=> fixed bug while loading user details

app/Http/Controllers/Actions/Report/GenerateReportAction.php, app/Http/Requests/TimelogReportRequest.php, app/Models/User.php
when a non-admin hits the display-report api, the user should only get thier own report
=> Pttb 395 backend display report for member

app/Http/Controllers/UserController.php
=> sent user details as a resource

app/Http/Controllers/Actions/Report/GeneratePdfAction.php, app/Http/Controllers/Actions/Report/GenerateReportAction.php
fixed pdf report generation for non-admins
=> fixed pdf report for non-admin
